from tkinter import*
class Hello(Frame):
    def __init__(self,box):
        super().__init__(box)
        self.lbl0=Label(self,text="              REGISTRATION FORM",font="bold")
        self.lbl1=Label(self,text="Username")
        self.lbl2=Label(self,text="Email-ID")
        self.lbl3=Label(self,text="Mobile Number")
        self.lbl4=Label(self,text="Password")
        self.lbl5=Label(self,text="Confirm Password")
        self.entry_1=Entry(self)
        self.entry_2=Entry(self)
        self.entry_3=Entry(self)
        self.entry_4=Entry(self,show="*")
        self.entry_5=Entry(self,show="*")
        
        self.lbl0.grid(row=0,padx=7,pady=7)
        self.lbl1.grid(row=2,padx=7,pady=7)
        self.lbl2.grid(row=3,padx=7,pady=7)
        self.lbl3.grid(row=4,padx=7,pady=7)
        self.lbl4.grid(row=5,padx=7,pady=7)
        self.lbl5.grid(row=6,padx=7,pady=7)
        self.entry_1.grid(row=2,column=1)
        self.entry_2.grid(row=3,column=1)
        self.entry_3.grid(row=4,column=1)
        self.entry_4.grid(row=5,column=1)
        self.entry_5.grid(row=6,column=1)
        self.button1=Button(self,bg="light blue", fg="red",text="Sign Up")
        self.button1.grid(row=7,column=1,padx=7,pady=7)
        self.pack()
root=Tk()
h=Hello(root)
root.minsize(350,200)
root.mainloop()
  
